"""initial create statscounts

Revision ID: 75e93ce7659e
Revises: 
Create Date: 2020-05-13 15:50:41.328651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e93ce7659e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print('==upgrade table statscounts==')
    op.create_table('statscounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statscounts')
    # ### end Alembic commands ###
