"""add column description

Revision ID: a4e5d48486ef
Revises: 75e93ce7659e
Create Date: 2020-05-13 15:54:33.684905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e5d48486ef'
down_revision = '75e93ce7659e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statscounts', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statscounts', 'description')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('sysinfos')
    op.drop_table('students')
    # ### end Alembic commands ###
